### ISSUE TITLE
Phoenix production mariaex losing connection

### ISSUE THREAD

**Issue by tdejager** [xerions/mariaex#103]
Hi,

I have a problem with a phoenix server running with the mix environment in production mode. The used MariaEx version os 0.5.0 as required by Ecto. The environment is an ubuntu 14.04 server running on AWS Ec2.

Sometimes the MariaEx GenServer seems to stop, and immediately restarts afterwards. This also happens when no requests are made to the database. It happens every hour or so.

>  08:50:31.594 [error] GenServer #PID<0.439.0> terminating
** (stop) %Mariaex.Error{mariadb: nil, message: "connection closed"}

Is there any way to acquire more info to what is going wrong? Or do you have any idea?

Thanks for the great work!

Tim

**Comment by liveforeverx** [comment]
Hi!

Can you try to configure adapter (more documentation on `Mariaex.Connection.start_link`) with:

```
keepalive: true
```

Please check, if it helps.

**Comment by tdejager** [comment]
After adding this option, and monitoring the process for a while. The error seems to be gone, maybe add this to the documentation, if someone is having problems?

Thanks!

**Comment by liveforeverx** [comment]
Thanks for feedback!
