### ISSUE TITLE
Incorrect behaviour for queries, started with spaces

### ISSUE THREAD

**Issue by Rakoth** [xerions/mariaex#105]
```elixir
sql = """
  INSERT INTO tbl (id)
  VALUES (?)
"""
Mariaex.query(conn, sql, [1])
```
failing with `** (ArgumentError) unsupported parameterized query`

**Comment by liveforeverx** [comment]
Hi!

Thats true and it is expected behaviour, you should sanitize input in your code before using it as query, because we wanted to avoided string manipulation, which is not needed in most cases.
