### ISSUE TITLE
(FunctionClauseError) no function clause matching in Mariaex.Protocol.ping_handle/3

### ISSUE THREAD

**Issue by somlor** [xerions/mariaex#106]
Since upgrading to `v0.7.2`, I've been periodically seeing this error:
```
[error] GenServer #PID<0.921.0> terminating
** (FunctionClauseError) no function clause matching in Mariaex.Protocol.ping_handle/3
    (mariaex) lib/mariaex/protocol.ex:568: Mariaex.Protocol.ping_handle({:packet, 7, 1, {:bin_row, <<0, 0, 0, 2, 0, 0, 0>>}, <<0, 0, 0, 2, 0, 0, 0>>}, :ping, %Mariaex.Protocol{buffer: "", cache: 6029489, catch_eof: false, connection_id: #PID<0.921.0>, connection_ref: #Reference<0.0.4.2371>, lru_cache: {100, 6033575}, opts: [socket_options: [], sock_type: :tcp, cache_size: 100, timeout: 5000, otp_app: :example, repo: Example.Repo, adapter: Ecto.Adapters.MySQL, username: "dbuser", password: "", database: "example_dev", hostname: "localhost", port: 3306], protocol57: false, rows: [], seqnum: 0, sock: {Mariaex.Connection.Tcp, #Port<0.39787>}, state: :bin_rows, state_data: {0, 0}, timeout: 5000})
    (db_connection) lib/db_connection/connection.ex:313: DBConnection.Connection.handle_info/2
    (connection) lib/connection.ex:812: Connection.handle_async/3
    (stdlib) gen_server.erl:615: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:681: :gen_server.handle_msg/5
    (stdlib) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
Last message: :timeout
```

Have not quite identified a pattern yet, but any ideas? Please let me know if you need more information, or need any kind of help investigating or fixing. Thanks!

**Comment by liveforeverx** [comment]
Hi! Thanks for reporting!

How long are typical queries before it happens, which are running? Which MySQL/MariaDB version do you use?

Can you set `:idle_timeout` to `60000` on adapter configuration to test if that changes something.

**Comment by liveforeverx** [comment]
Ok, I have found.

**Comment by somlor** [comment]
@liveforeverx Fantastic. FWIW I am seeing the error in development on OSX MySQL version `5.6.29` and in staging on AWS Aurora which uses a forked version of MySQL `5.6`, not sure exact point version. I tried setting `idle_timeout: 6000` in dev, but still saw the error after some time. Let me know if there's anything else I can do.

**Comment by liveforeverx** [comment]
Yes, please, recheck with version: `0.7.3`

**Comment by somlor** [comment]
Ok, I've upgraded and have tested hitting several endpoints. I believe previously error would have happened by now, but so far so good. :+1: Thanks!

**Comment by liveforeverx** [comment]
@somlor Thanks!
