### ISSUE TITLE
BIT(1) type cannot load `<<1>>` as type :boolean

### ISSUE THREAD

**Issue by paulgithub** [xerions/mariaex#107]
When reading a boolean value from the database which is represented as a BIT(1) in the MySQL server (version 5.5.29) and using this value in model as a :boolean The following error is displayed:

** (exit) an exception was raised:
    ** (ArgumentError) cannot load `<<1>>` as type :boolean
        (ecto) lib/ecto/schema.ex:982: Ecto.Schema.load!/3
        (ecto) lib/ecto/schema.ex:974: anonymous fn/3 in Ecto.Schema.do_load/4
        (elixir) lib/enum.ex:1473: Enum."-reduce/3-lists^foldl/2-0-"/3
        (ecto) lib/ecto/schema.ex:972: Ecto.Schema.do_load/4
        (ecto) lib/ecto/schema.ex:957: Ecto.Schema.__load__/6
        (ecto) lib/ecto/adapters/sql.ex:519: anonymous fn/3 in Ecto.Adapters.SQL.process_row/3
        (elixir) lib/enum.ex:1151: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
        (ecto) lib/ecto/adapters/sql.ex:513: Ecto.Adapters.SQL.process_row/3
        (elixir) lib/enum.ex:1088: Enum."-map/2-lists^map/1-0-"/2
        (ecto) lib/ecto/adapters/sql.ex:283: Ecto.Adapters.SQL.decode/2
        (stdlib) timer.erl:166: :timer.tc/1
        (ecto) lib/ecto/adapters/sql.ex:278: Ecto.Adapters.SQL.decode/3
        (ecto) lib/ecto/adapters/sql.ex:225: Ecto.Adapters.SQL.query/5
        (ecto) lib/ecto/adapters/sql.ex:183: Ecto.Adapters.SQL.query!/5
        (ecto) lib/ecto/adapters/sql.ex:481: Ecto.Adapters.SQL.execute/6
        (ecto) lib/ecto/repo/queryable.ex:95: Ecto.Repo.Queryable.execute/5
        (ecto) lib/ecto/repo/queryable.ex:15: Ecto.Repo.Queryable.all/4
        (ecto) lib/ecto/repo/queryable.ex:44: Ecto.Repo.Queryable.one/4

Versions from mix.lock:
mariaex, "0.7.3"
phoenix, "1.1.4"
ecto, "1.1.4"
phoenix_ecto, "2.0.1"

NOTE: I am able to get mariaex version 0.6.x working by adding the fix for BIT(1) as per my previous issue:  BIT(1) type fails on read #89 

Reading your previous response on issue #89 I assume that it will only work if using ecto 2.x and NOT ecto 1.x, is this correct?

**Comment by liveforeverx** [comment]
@paulgithub I think, further it should be fixed in ecto. By matching <<1>> and <<0>> to boolean in MySQL adapter.

CC: @josevalim @ericmj @fishcakez Ideas?

**Comment by josevalim** [comment]
it is alright to solve it in the Ecto adapter.

**Comment by liveforeverx** [comment]
@paulgithub Can you open issue in ecto, please?

I think, it should be added here: https://github.com/elixir-lang/ecto/blob/master/lib/ecto/adapters/mysql.ex#L109-L111 (I thought, that I have changed it for ecto 2.0, but can't find changes there).

@paulgithub Can you apply this patch to ecto v1.1 and test? 

```
diff --git a/lib/ecto/adapters/mysql.ex b/lib/ecto/adapters/mysql.ex
index 73cd825..0c03e62 100644
--- a/lib/ecto/adapters/mysql.ex
+++ b/lib/ecto/adapters/mysql.ex
@@ -93,6 +93,8 @@ defmodule Ecto.Adapters.MySQL do
     do: super(type, json_library.decode!(binary))
   def load(:map, binary) when is_binary(binary),
     do: super(:map, json_library.decode!(binary))
+  def load(:boolean, <<0>>), do: {:ok, false}
+  def load(:boolean, <<1>>), do: {:ok, true}
   def load(:boolean, 0), do: {:ok, false}
   def load(:boolean, 1), do: {:ok, true}
   def load(type, value), do: super(type, value)
```

**Comment by paulgithub** [comment]
I can confirm that the patch above works.

I have opened a new issue on the ecto github page: https://github.com/elixir-lang/ecto/issues/1366

Thanks for the speedy response.

**Comment by josevalim** [comment]
We can close this one. :)
