### ISSUE TITLE
parsing of server version number fails

### ISSUE THREAD

**Issue by uzleepito** [xerions/mariaex#108]
When connecting to MySQL, the server's version number is parsed via the standard Elixir function: `Version.Parser.parse_version/2`.  This returns `:error` when attempting to parse "5.1.46sp1-log".  I believe versions should be parsed some other ways here.

**Comment by liveforeverx** [comment]
@uzleepito I will implement own stable version parsing for version numbers.

**Comment by liveforeverx** [comment]
@uzleepito fixed in `v0.7.4`
