### ISSUE TITLE
Latest mariaex seems incompatible with ecto 2.0 beta

### ISSUE THREAD

**Issue by kennyballou** [xerions/mariaex#109]
After upgrading both `mariaex` to `0.7.3` and `ecto` to `2.0.0-beta.2`, I'm
receiving the following in my phoenix project's `mix test` (during the
compiling phase):

    lib/ecto/adapters/mysql/connection.ex:3: warning: undefined behaviour function child_spec/1 (for behaviour Ecto.Adapters.SQL.Connection)
    lib/ecto/adapters/mysql/connection.ex:3: warning: undefined behaviour function execute/4 (for behaviour Ecto.Adapters.SQL.Connection)
    lib/ecto/adapters/mysql/connection.ex:3: warning: undefined behaviour function prepare_execute/5 (for behaviour Ecto.Adapters.SQL.Connection)

Followed by this error:

    ** (Mix) Could not start application my_project: MyProject.start(:normal, []) returned an error: shutdown: failed to start child: MyProject.Repo
    ** (EXIT) an exception was raised:
        ** (UndefinedFunctionError) undefined function Ecto.Adapters.MySQL.Connection.child_spec/1
            (ecto) Ecto.Adapters.MySQL.Connection.child_spec([name: MyProject.Repo.Pool, otp_app: :my_project, repo: MyProject.Repo, adapter: Ecto.Adapters.MySQL, username: "root", password: "mysql", database: "my_project_test", hostname: "mysql", pool_timeout: 5000, timeout: 15000, pool: DBConnection.Ownership, adapter: Ecto.Adapters.MySQL, username: "root", password: "mysql", database: "my_project_test", hostname: "mysql"])
            (ecto) lib/ecto/repo/supervisor.ex:92: Ecto.Repo.Supervisor.init/1
            (stdlib) supervisor.erl:287: :supervisor.init/1
            (stdlib) gen_server.erl:328: :gen_server.init_it/6
            (stdlib) proc_lib.erl:240: :proc_lib.init_p_do_apply/3

This error seems obvious after seeing the warnings above. But I'm not sure
there is much I can do to resolve it from here without digging into the
`mariaex` code, though I'm open to trying.

I mention this on these versions because the `ecto` project is currently
listing the two as compatible. I also didn't see another issue mentioning this here nor in `ecto`.

## Other Notes ##

In attempting to solve this issue, I've nuked both `_build` and `deps`, to no
avail. I've also tried using version `0.6.5` of `mariaex`, which was the
version I was using before today (since I was waiting for another [issue][1] to
be resolved).

## Version information ##

*   Arch Linux

        Linux Daeva 4.4.5-1-ARCH #1 SMP PREEMPT Thu Mar 10 07:38:19 CET 2016 x86_64 GNU/Linux

*   Elixir Version:

        Erlang/OTP 18 [erts-7.3] [source] [64-bit] [smp:8:8] [async-threads:10] [hipe] [kernel-poll:false]

        Elixir 1.2.4

*   "MyProject" Dependency information:

        %{"comeonin": {:hex, :comeonin, "2.3.1"},
          "connection": {:hex, :connection, "1.0.2"},
          "cowboy": {:hex, :cowboy, "1.0.4"},
          "cowlib": {:hex, :cowlib, "1.0.2"},
          "db_connection": {:hex, :db_connection, "0.2.5"},
          "decimal": {:hex, :decimal, "1.1.1"},
          "earmark": {:hex, :earmark, "0.2.1"},
          "ecto": {:hex, :ecto, "2.0.0-beta.2"},
          "ex_doc": {:hex, :ex_doc, "0.11.4"},
          "gettext": {:hex, :gettext, "0.10.0"},
          "json_web_token": {:hex, :json_web_token, "0.2.4"},
          "jwt_claims": {:hex, :jwt_claims, "0.0.3"},
          "mariaex": {:hex, :mariaex, "0.7.3"},
          "phoenix": {:hex, :phoenix, "1.1.4"},
          "phoenix_ecto": {:hex, :phoenix_ecto, "3.0.0-beta.2"},
          "plug": {:hex, :plug, "1.1.3"},
          "poison": {:hex, :poison, "1.5.2"},
          "poolboy": {:hex, :poolboy, "1.5.1"},
          "ranch": {:hex, :ranch, "1.2.1"}}

[1]: https://github.com/xerions/mariaex/issues/99

**Comment by liveforeverx** [comment]
`(UndefinedFunctionError) undefined function Ecto.Adapters.MySQL.Connection.child_spec/1` - please use ecto 2.0 from master, I think, that the ecto with MySQL is not released yet as beta.

**Comment by kennyballou** [comment]
Yep, totally worked, thanks!
