### ISSUE TITLE
INSERT params with special chars to latin1 table does not work properly

### ISSUE THREAD

**Issue by iaddict** [xerions/mariaex#110]
When inserting utf8 special chars to a latin1 encoded database with params, the stored param value gets garbled. It looks like the utf8 bytes get inserted instead of latin1 encoded chars.

Following an example iex session:

```elixir
iex(21)> Mariaex.query(p, "INSERT INTO category SET name='Löläla'")  # this gets inserted as expected
iex(22)> Mariaex.query(p, "INSERT INTO category SET name=?", ["Löläla"]) # id=126 which is garbled
iex(23)> Mariaex.query(p, "SELECT * FROM category ORDER BY id DESC LIMIT 2")
{:ok,
 %Mariaex.Result{columns: ["id", "parent_id", "name", "description", "public",
   "order_id"], command: :select, connection_id: nil, last_insert_id: nil,
  num_rows: 2,
  rows: [[126, 0, "LÃ¶lÃ¤la", nil, "TRUE", ""],
   [125, 0, "Löläla", nil, "TRUE", ""]]}}
```

```sql
-- following the table DDL
CREATE TABLE `category` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(30) NOT NULL DEFAULT '',
  KEY `name` (`name`)
) ENGINE=MyISAM AUTO_INCREMENT=127 DEFAULT CHARSET=latin1;
```

The used Mariaex version is 0.7.4 with Elixir 1.2.4 and a MySQL Community Server version 5.6.21.

Many thanks for your great work!

I hope my explanation helps to find the bug.

**Comment by liveforeverx** [comment]
@iaddict Hi! Default charset is `utf8`, you can configure charset via: `charset` options (see: `Mariaex.start_link`). Can you try configure it to use charset latin1 and checks if it helps?

**Comment by iaddict** [comment]
Hi! Thanks for your quick reply.

Actually it makes things worse. Because now the connection is set to latin1, the utf8 strings are in both cases saved garbled to the database. If I understand the `SET NAMES utf8` right, it means which charset is used by the client. MySQL saves things accordingly.

Reading (SELECT ...) from a legacy database with all data latin1 encoded and the default setting of `[charset: :utf8]` works just fine. It's just insert and update that cause data to get garbled.

**Comment by iaddict** [comment]
@liveforeverx Hi again! I did some more investigations and found the following.
There is a mysql driver for Erlang which I did check. It uses a different field type to encode binary params, see: https://github.com/mysql-otp/mysql-otp/blob/master/src/mysql_protocol.erl#L745

I switched on line query.ex#103 the field type from : field_type_blob to :field_type_var_string, so the line reads:
```elixir
    {0, :field_type_var_string, << to_length_encoded_integer(byte_size(bin)) :: binary, bin :: binary >>}
```

This change fixes the encoding issues, but I am not sure what side effects this change will have for other params that match encode_param with binaries.

Maybe the encode_param function can be changed to something like this:
```elixir
  defp encode_param(bin) when is_binary(bin) do
    field_type = if String.valid?(bin), do: :field_type_var_string, else: :field_type_blob
    {0, field_type, << to_length_encoded_integer(byte_size(bin)) :: binary, bin :: binary >>}
  end
```

What do you think?
If you think that this is the right way to go, I can write a test and submit a pull request.

**Comment by liveforeverx** [comment]
@iaddict We need to do the same, always use `:field_type_var_string` until nobody runs in problem with it. And not analyse string in runtime from performance reasons.
