### ISSUE TITLE
Support for JSON data type

### ISSUE THREAD

**Issue by belaustegui** [xerions/mariaex#119]
Quoting from the Ecto documentation (emphasis mine): 

> In order to support maps, different databases may employ different techniques. For example, PostgreSQL will store those values in jsonb fields, allowing you to even query parts of it. **MySQL and MSSQL, on the other hand, do not yet provide a JSON type, so the value will be stored in a text field**.

Since recent versions of MySQL have a [JSON data type](https://dev.mysql.com/doc/refman/5.7/en/json.html) I am wondering if this is still the case.
How does the _mariaex_ adapter store fields defined with a type of _map_ in the database? Are they stored using the JSON type or in a text field?

**Comment by liveforeverx** [comment]
@belaustegui they are stored in text field, as I know

Should `mariaex` natively support maps and by themself decide, if it should store as map or text or should it be done in adapter @josevalim @ericmj @fishcakez ?

**Comment by josevalim** [comment]
I don't think it is the adapter responsibility to "fake" types it does not
really support.

On Tuesday, June 7, 2016, Dmitry Russ(Aleksandrov) <notifications@github.com>
wrote:

> @belaustegui <https://github.com/belaustegui> they are stored in text
> field, as I know
>
> Should mariaex natively support maps and by themself decide, if it should
> store as map or text or should it be done in adapter @josevalim
> <https://github.com/josevalim> @ericmj <https://github.com/ericmj>
> @fishcakez <https://github.com/fishcakez> ?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/xerions/mariaex/issues/119#issuecomment-224262488>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAAlbgPpi6s5DhOk8qvhiGNuHMCEUMz9ks5qJWEQgaJpZM4Iv19x>
> .
>


-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by ericmj** [comment]
@josevalim Do you mean it's not the drivers responsibility? It's
exactly the adapters job to fake types that exist in ecto but not on the
underlying database. The driver doesn't know it's being used by ecto.

On Tuesday, 7 June 2016, José Valim <notifications@github.com> wrote:

> I don't think it is the adapter responsibility to "fake" types it does not
> really support.
>
> On Tuesday, June 7, 2016, Dmitry Russ(Aleksandrov) <
> notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>>
> wrote:
>
> > @belaustegui <https://github.com/belaustegui> they are stored in text
> > field, as I know
> >
> > Should mariaex natively support maps and by themself decide, if it should
> > store as map or text or should it be done in adapter @josevalim
> > <https://github.com/josevalim> @ericmj <https://github.com/ericmj>
> > @fishcakez <https://github.com/fishcakez> ?
> >
> > —
> > You are receiving this because you were mentioned.
> > Reply to this email directly, view it on GitHub
> > <https://github.com/xerions/mariaex/issues/119#issuecomment-224262488>,
> > or mute the thread
> > <
> https://github.com/notifications/unsubscribe/AAAlbgPpi6s5DhOk8qvhiGNuHMCEUMz9ks5qJWEQgaJpZM4Iv19x
> >
> > .
> >
>
>
> --
>
>
> *José Valimwww.plataformatec.com.br
> <http://www.plataformatec.com.br/>Founder and Director of R&D*
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/xerions/mariaex/issues/119#issuecomment-224266715>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AATV2jzLUySIDzX_m8KqMjo46bFCka9Cks5qJWWMgaJpZM4Iv19x>
> .
>


-- 
Eric Meadows-Jönsson

**Comment by josevalim** [comment]
Let me expand what I mean by "fake". I think it is the job of the adapter to translate between Elixir and database types. I don't think it is the job of the adapter to provide types that do not really exist in the database. :)

**Comment by liveforeverx** [comment]
@ericmj @josevalim So, this is possible to have in `mariaex` for MySQL => 5.7.9 https://github.com/xerions/mariaex/blob/json_support/test/query_test.exs#L568-L570

Means, it is possible to natively support json, which were added to new version of MySQL

**Comment by liveforeverx** [comment]
@ericmj @josevalim Since, we need to support older versions of MySQL, somewhere need to be a switch, for using of json natively or as fake type. My big question, where and how to make this switch.

**Comment by ericmj** [comment]
@josevalim said he thought faking was a bad idea so I think you should just
let it crash or raise an error message win older versions of th db.

On Wednesday, 8 June 2016, Dmitry Russ(Aleksandrov) <
notifications@github.com> wrote:

> @ericmj <https://github.com/ericmj> @josevalim
> <https://github.com/josevalim> Since, we need to support older versions
> of MySQL, somewhere need to be a switch, for using of json natively or as
> fake type. My big question, where and how to make this switch.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/xerions/mariaex/issues/119#issuecomment-224528675>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AATV2q_5u8AjT7lMClivNvmnmS7G5Z_kks5qJoLIgaJpZM4Iv19x>
> .
>


-- 
Eric Meadows-Jönsson

**Comment by josevalim** [comment]
@liveforeverx that's a reasonable feature then. You can support maps and encode it accordingly depending if the feature is enabled or not. I would honestly support this feature as a connection option such as `encode_maps_as: :text | :jdoc`

@ericmj if the database supports it in recent versions, I think it is reasonable for the adapter to handle it then for older versions otherwise the MySQL version would leak (for example, Ecto would need to be aware of the MySQL version).

**Comment by ericmj** [comment]
I don't think faking json is a necessary feature. Ecto supports postgres
versions that do not have Kano support and would just crash when using :map.

Checking the database version from the adapter shouldn't be an issue as
long as the driver exposes it as an API.

On Wednesday, 8 June 2016, José Valim <notifications@github.com> wrote:

> @liveforeverx <https://github.com/liveforeverx> that's a reasonable
> feature then. You can support maps and encode it accordingly depending if
> the feature is enabled or not. I would honestly support this feature as a
> connection option such as encode_maps_as: :text | :jdoc
>
> @ericmj <https://github.com/ericmj> if the database supports it in recent
> versions, I think it is reasonable for the adapter to handle it then for
> older versions otherwise the MySQL version would leak (for example, Ecto
> would need to be aware of the MySQL version).
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/xerions/mariaex/issues/119#issuecomment-224529468>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AATV2hH6LSUjgEKnfF-t2xWWS49urJJpks5qJoOagaJpZM4Iv19x>
> .
>


-- 
Eric Meadows-Jönsson

**Comment by belaustegui** [comment]
That is exactly what I was thinking when I opened the issue, to leverage the JSON data type that is already provided by MySQL :)

If I can help in any way please tell me.
Thanks!

**Comment by belaustegui** [comment]
I am interested in this issue and I could try to send a pull request to fix it myself. I would only need a small guideline about where to look into and where to put the implementation.

I've been looking a bit into the elixir-ecto/postgrex code to see how the PostgreSQL adapter handles this, but I am not having luck finding it :disappointed:

**Comment by mgwidmann** [comment]
You should know that the driver crashes when it encounters a true JSON column because this line does not have a definition for `245`: https://github.com/xerions/mariaex/blob/master/lib/mariaex/messages.ex#L82
(generated and reproducible by adding https://github.com/mgwidmann/flames to any phoenix project using MySQL)
```
[error] #PID<0.808.0> running MyApp.Endpoint terminated
Server: localhost:4000 (http)
Request: GET /errors/api/errors
** (exit) an exception was raised:
    ** (FunctionClauseError) no function clause matching in Mariaex.Messages.__type__/2
        (mariaex) lib/mariaex/messages.ex:76: Mariaex.Messages.__type__(:type, 245)
        (mariaex) lib/mariaex/row_parser.ex:17: anonymous fn/2 in Mariaex.RowParser.decode_init/1
        (elixir) lib/enum.ex:1755: Enum."-reduce/3-lists^foldl/2-0-"/3
        (mariaex) lib/mariaex/row_parser.ex:16: Mariaex.RowParser.decode_init/1
        (mariaex) lib/mariaex/protocol.ex:537: Mariaex.Protocol.bin_rows_recv/2
        (mariaex) lib/mariaex/protocol.ex:506: Mariaex.Protocol.binary_query_recv/1
        (mariaex) lib/mariaex/protocol.ex:490: Mariaex.Protocol.binary_query_recv/2
        (db_connection) lib/db_connection.ex:957: DBConnection.handle/4
        (db_connection) lib/db_connection.ex:1077: DBConnection.describe_run/5
        (db_connection) lib/db_connection.ex:1141: anonymous fn/4 in DBConnection.run_meter/5
        (db_connection) lib/db_connection.ex:1198: DBConnection.run_begin/3
        (db_connection) lib/db_connection.ex:584: DBConnection.prepare_execute/4
        (ecto) lib/ecto/adapters/sql.ex:243: Ecto.Adapters.SQL.sql_call/6
        (ecto) lib/ecto/adapters/sql.ex:431: Ecto.Adapters.SQL.execute_and_cache/7
        (ecto) lib/ecto/repo/queryable.ex:130: Ecto.Repo.Queryable.execute/5
        (ecto) lib/ecto/repo/queryable.ex:35: Ecto.Repo.Queryable.all/4
        (flames) lib/web/controllers/errors_controller.ex:9: Flames.ErrorsController.index/2
        (flames) lib/web/controllers/errors_controller.ex:2: Flames.ErrorsController.action/2
        (flames) lib/web/controllers/errors_controller.ex:2: Flames.ErrorsController.phoenix_controller_pipeline/2
```

You can find lots of reports from PHP developers about this, like this one:
http://stackoverflow.com/questions/37898950/error-245-in-mysql-prepare

All of them state that the `245` number coming from MySQL is the JSON column type. Should this be handled like a string on the Elixir side, and then Ecto should parse it? What does the postgres driver do?

**Comment by mgwidmann** [comment]
Also just curious, why isn't this branch in a PR? https://github.com/xerions/mariaex/tree/json_support
