### ISSUE TITLE
mariaex is not supporting local languages while inserting into Mysql

### ISSUE THREAD

**Issue by tmadankumar** [xerions/mariaex#130]
I am trying to insert one indian language string into mysql database using Ecto Repo.insert, but in database that value of that column showing like ???????????????

while creating database in mysql i am using ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci; for unicode support, and inside elixir model i am using column type as string( field :displayname, :string )

I got confirmation from Ecto Team, this issue from mariaex, need support from anybody to fix my issue.

Environment

Elixir version (Elixir 1.3.2):
Database and version (MySQL 5.6.27 ):
Ecto version (1.1.9):
Database adapter and version (mariaex 0.7.7 ):
Operating system: Ubuntu 14.04.3 LTS
Current behavior

String : ಆಗ್ತಾಇಲ್ಲ
After insert into mysql db using Repo.insert, in DB it is showing like ???????

Expected behavior

String : ಆಗ್ತಾಇಲ್ಲ
After insert into mysql db using Repo.insert, in DB it should show ಆಗ್ತಾಇಲ್ಲ

**Comment by stonely2012** [comment]
i have problem

**Comment by stonely2012** [comment]
I change line 103 of query.ex
from
do: {0, :field_type_var_string, << to_length_encoded_integer(byte_size(bin)) :: binary, bin :: binary >>}
to
do: {0, :field_type_blob, << to_length_encoded_integer(byte_size(bin)) :: binary, bin :: binary >>}

It's work now. But it's conflict with issue 110 (https://github.com/xerions/mariaex/issues/110)
