### ISSUE TITLE
MySQL handshake auth_plugin_data2

### ISSUE THREAD

**Issue by jdangerx** [xerions/mariaex#133]
Hi, I'm using Mariaex to connect to Sphinx Search, which implements the MySQL 4.1 protocol. For the `auth_plugin_data2` field of the initial handshake, Sphinx sends a non-NUL terminated string (`string.fixlen`, as specified [here](https://dev.mysql.com/doc/internals/en/connection-phase-packets.html#packet-Protocol::Handshake)). This causes a pattern match in [line 94](https://github.com/xerions/mariaex/blob/master/lib/mariaex/messages.ex#L94
) of `messages.ex`:
```elixir
    auth_plugin_data2 :string #max(13, length_auth_plugin_data - 8), :string
```
Since we are looking for a NUL terminated string. I see there's a comment there that indicates we want to pull `max(13, length_auth_plugin_data - 8)` bytes - so maybe you've considered this and then thought better of it. In any case, it looks like we need another pattern match in `Mariaex.Coder.match` to fully meet the MySQL spec.

**Comment by liveforeverx** [comment]
Thanks!
