### ISSUE TITLE
Whats the current state of mariaex project?

### ISSUE THREAD

**Issue by driv3r** [xerions/mariaex#146]
From what I can see there are some enhancements suggested by @josevalim about a year ago, milestones doesn't seem to be used anymore - so where the project stands at the moment? Any kind of road map?  any need for PRs?

Best,
Leszek

**Comment by liveforeverx** [comment]
@driv3r Hi! Project is stable and used by different people and companies in production, including myself. No, there is no any kind of roadmap, I have tried to establish roadmap in a times, where some decisions were changed/implemented quicker as roadmap and the roadmap was always outdated. Absence of roadmap was not a problem yet. PRs are welcome. For bigger PRs, better to start from issue and discussion on it.
