### ISSUE TITLE
Proper way to handle mariaex/dbconnection process?

### ISSUE THREAD

**Issue by jordan0day** [xerions/mariaex#149]
I've asked this question over on [elixirforum](https://elixirforum.com/t/how-to-properly-use-mariaex-dbconnection/2383) but I thought I might check here as well. I'm just curious what the correct pattern for handling Mariaex processes is for a long-running application, not using Ecto.

Should I start up the Mariaex process (via `Mariaex.start_link/1`) and then hold on to that pid, using it for all subsequent queries? Or should I stop that process as soon as I'm done with a particular query, and spin up a new process when I need to make another query later on? I know under the covers using `DBConnection` all the connection pooling stuff should be handled for me, but I tried to dig through Ecto's codebase to see how it was done there and came up more confused than I was when I started.

**Comment by jordan0day** [comment]
Sorry, loaded up on cold medicine today and wasn't thinking clearly nor parsing the existing code clearly.

**Comment by acrolink** [comment]
@jordan0day Would you mind what you have done eventually? Open and close connections, or using some global pid to do subsequent queries?

**Comment by jordan0day** [comment]
I ended up using a global pid running under a supervisor. For anyone else looking at this, this blog post (linked in the elixirforum thread) is very similar to how I'm using it (scroll down to 'For mariaex, we need to...'):
https://www.amberbit.com/blog/2018/6/12/executing_raw_sql_queries_in_elixir/
