### ISSUE TITLE
Use fields from Mariaex.Result struct

### ISSUE THREAD

**Issue by sh4t4d33p** [xerions/mariaex#212]
I have written an Elixir script which sends a MySQL query to my database using the Mariaex library. The query works perfectly. Now, I want to use the num_rows field returned in the Mariaex.Result struct in my script. The code snippet is something like this:-  
```
if {:ok, %Mariaex.Result{num_rows: nil}} do
    IO.puts "Query Unsuccessful"
else
    IO.puts "Query Successful"
end  
```
I know the if-condition does not work properly. The goal of the condition is to check whether num_rows is 0 or not. I know the problem is not with the whole code. I just need help to construct the if-condition, i.e., this part: `{:ok, %Mariaex.Result{num_rows: nil}}`. How should I modify the condition, so that the above code snippet works correctly?

**Comment by surik** [comment]
You probably need `case`:

```
case Result do
   {:ok, %Mariaex.Result{num_rows: nil}} ->
     IO.puts "Query Unsuccessful"
  ->
     IO.puts "Query Successful"
end  
```

This is really a basic language question and not related to `mariaex`. I would suggest you read [Introduction to Elixir](https://elixir-lang.org/getting-started/introduction.html) or use `beginners` channel in the official [Slack group](https://elixir-slackin.herokuapp.com) for such questions.

**Comment by sh4t4d33p** [comment]
I'm sorry, but your code does not work. Like I said, the problem is with the condition and not the if-construct. The condition I have mentioned is not the correct way to return the number of rows affected. The output will always be erroneous. That's why I posted this issue.

**Comment by surik** [comment]
What kind of query do you send? What do you have as `Mariaex.Result`?

**Comment by sh4t4d33p** [comment]
I am sending a simple update query. The query is working perfectly, because the changes are reflected in the database. The number of rows affected should be 1. However, in the iex, I am getting the following result:
`%Mariaex.Result{columns: nil, connection_id: nil, last_insert_id: nil, num_rows: nil, rows: nil}`
Its shows the num_rows is nil. Therefore, there is something wrong with the Mariaex.Result.

**Comment by surik** [comment]
```

**Comment by surik** [comment]
I did a simple update query with MariaDB 10.2.12 and mariaex 0.8.3:

```elixir
iex(1)> {:ok, p} = Mariaex.start_link(username: "root", database: "test")
{:ok, #PID<0.1137.0>}

iex(2)> Mariaex.query(p, "CREATE TABLE test1 (id serial, title text)")
{:ok,
 %Mariaex.Result{columns: [], connection_id: nil, last_insert_id: 0, num_rows: 0, rows: nil}}

iex(3)> Mariaex.query(p, "INSERT INTO test1 VALUES(1, 'test')")
{:ok,
 %Mariaex.Result{columns: [], connection_id: nil, last_insert_id: 1, num_rows: 1, rows: nil}}

iex(4)> Mariaex.query(p, "UPDATE test1 SET id = id + 1;")
{:ok,
 %Mariaex.Result{columns: [], connection_id: nil, last_insert_id: 0, num_rows: 1, rows: nil}}
```

Could you please provide minimal test example?

**Comment by sh4t4d33p** [comment]
The output is fine when I write queries through a terminal. But I am running an Elixir script which is making the queries. Also in the same script, I am printing the Mariaex.Result like this:-
`IO.puts Kernel.inspect(%Mariaex.Result{})`
The number of rows affected should be 1, but instead I get the following output:-
`%Mariaex.Result{columns: nil, connection_id: nil, last_insert_id: nil, num_rows: nil, rows: nil}`

**Comment by surik** [comment]
This is correct:
```elixir
iex(3)> IO.puts Kernel.inspect(%Mariaex.Result{})
%Mariaex.Result{columns: nil, connection_id: nil, last_insert_id: nil, num_rows: nil, rows: nil}
:ok
```

Are you expecting `Mariaex.Result` as a shared data structure which changes after each query call?  Do you assign the result of `Mariaex.query/2` to some variable in your script?

**Comment by sh4t4d33p** [comment]
I thought the Mariaex.Result would be different after each call. No, I haven't  assigned the result of `Mariaex.query/2` to any variable. Could you please show me how to get the updated result of my queries?

**Comment by surik** [comment]
Like this

**Comment by surik** [comment]
Like this:

```elixir
result = Mariaex.query(p, "UPDATE test1 SET id = id + 1;")
case result do
   {:ok, %Mariaex.Result{num_rows: nil}} ->
     IO.puts "Query Unsuccessful"
  ->
     IO.puts "Query Successful"
end 
```

I'm closing this because it is not related to mariaex.
