### ISSUE TITLE
Deploy 0.9.0 into hex.pm

### ISSUE THREAD

**Issue by jonasrichard** [xerions/mariaex#221]
I see that now this library supports the Elixir 1.3 dates, but it would be use to download it through hex. I have seen that the changes are 7 months old, probably it is stable enough to release them under a new version.

**Comment by fishcakez** [comment]
I think there are a couple of bugs to fix and completion of JSON support before a 0.9. If you need date support I would suggest using git.

**Comment by jonasrichard** [comment]
Ok, then I close this issue. I just wasn't sure why this time+type thing is blocked here.
