### ISSUE TITLE
leaks connections

### ISSUE THREAD

**Issue by vans163** [xerions/mariaex#223]
Connections to database grow and grow and grow and grow, please implement a simple monitor on the parent pid and graceful close.

```elixir
Enum.each 1..1000, & :erlang.spawn(fn(_)->
	{:ok, pid} =  Mariaex.start_link(username: "root", password: "root")
end)
```
```
mysql > show processlist;
1000
```

pid is dead here, the connections should not hang.

https://github.com/xerions/mariaex/blob/a0aa98b77636070c93c08f06fe40aa092470551c/lib/mariaex/connection/tcp.ex#L3

If socket is not in active mode, perhaps process termination does not close it.

**Comment by fishcakez** [comment]
The process will exit if its parent exits due to the link, could you show a more complete example?

**Comment by vans163** [comment]
@fishcakez will it close the tcp_socket tho?

**Comment by fishcakez** [comment]
Yes they close because the gen tcp port is linked to the process or the SSL connection monitors the process. This is fundamental feature.

**Comment by vans163** [comment]
@fishcakez WHy did you close this lol? Did you even test what I submitted as the bug report??

```
Enum.each 1..1000, & :erlang.spawn(fn()->
    IO.puts &1
    {:ok, pid} =  Mariaex.start_link(username: "#{yOUR_USER}", password: "#{yOUR_PASS}")
end)
```
Now run 
```
show processlist;
```
1000

Now run
```
Enum.each 1..1000, & :erlang.spawn(fn()->
    IO.puts &1
    {:ok, pid} =  Mariaex.start_link(username: "#{yOUR_USER}", password: "#{yOUR_PASS}")
end)
```
Now run
```
show processlist;
```
2000

Clearly not a bug right? WOrking as intended.

**Comment by fishcakez** [comment]
@vans163 this is working as intended and is not a bug. I was confused by your first example as spawned process is exiting with reason normal so sends a normal exit signal to its child Mariaex processes. The Mariaex processes are not trapping exits so as part of how Erlang/OTP works as a fundamental feature, the child ignores the normal exit reason and continues to run. This is independent of active method on the socket, the socket will be closed if the process that owns its exits regardless of the active value (true, false, once, n). However the parent exiting with reason normal is the consistent feature between these examples, and so the Mariaex processes will never exit, and so the sockets won't either.

**Comment by vans163** [comment]
@fishcakez I love how bugs get labelled as "feature / working as intended" after a long explanation. Cheerio.

**Comment by liveforeverx** [comment]
@vans163 This is not a bug in mariaex, this is how Erlang and pretty every OTP compliant processes will work, please reread the answer from fishcakez and try to understand.

I give you practical example:

```elixir
Enum.each(1..50, fn (_) -> 
  :erlang.spawn(fn()->
    {:ok, pid} =  Mariaex.start_link(username: "root", password: "pw4docker", database: "test")
  end)
end)
```

Than you will see:

```
51 rows in set (0.00 sec)
```

But, if I will modify your code with error reason(that linking kills dependent process), than:

```elixir
Enum.each(1..50, fn (_) -> 
  :erlang.spawn(fn()->
    {:ok, pid} =  Mariaex.start_link(username: "root", password: "pw4docker", database: "test")
    Process.exit(self(), :i_am_broken)
  end)
end)
```

Than, afterwards, you will get:

```
1 row in set (0.00 sec)
```

This is how BEAM and any linked process will work inside of erlang.
Related documentation: http://erlang.org/doc/reference_manual/processes.html#id88487
Please, read carefully this sentence: 

```
A process can also be terminated if it receives an exit signal with another exit reason than normal, see Error Handling.
```

If it receives reason normal, linked process willn't be terminated.

**Comment by vans163** [comment]
The problem here is if you have a simple HTTP server, where the HTTP request opens a connection to the DB, queries, then gets reply. You leak connections. You cant throw an error or client wont get reply.

So you now need to go through the hassle of wrapping mariaex into a handle_call gen_server for no reason, adding an extra layer of abstraction.
