### ISSUE TITLE
Cancel queries if caller is known to be dead

### ISSUE THREAD

**Issue by josevalim** [xerions/mariaex#23]
If the MySQL protocol supports it, we can cancel long running queries if we know the caller died. This has been added to the TDS driver and will be available in the postgrex one too. Here is a reference implementation:

https://github.com/livehelpnow/tds/commit/19bc981364b6ffef39143a8f92c9392c835e6a3b

**Comment by josevalim** [comment]
Notice that the commit above is just part of it. We still need to continue reading the message before removing it from the queue or request its cancelation from the server if MySQL supports so.

**Comment by fishcakez** [comment]
This has been supported since DBConnection was used.
