### ISSUE TITLE
tests are failing with elixir master

### ISSUE THREAD

**Issue by liveforeverx** [xerions/mariaex#44]
Because of Mix.Shell.Cmd/2 changed to Mix.Shell.Cmd/3, the tests should be changed to something, what elixir 1.0.0 and 1.1.0 independent.

**Comment by umatomba** [comment]
backward compatibility with cmd/2  now in elixir master https://github.com/elixir-lang/elixir/commit/c9f84ae41e5575cb2d6c07eaa658e10477fe245e

**Comment by liveforeverx** [comment]
Thanks!
