### ISSUE TITLE
Starting with \n will cause query to fail

### ISSUE THREAD

**Issue by stikmanw** [xerions/mariaex#48]
mysql_conn |> Mariaex.Connection.query "
SELECT 1 
"

** (EXIT from #PID<0.51.0>) an exception was raised:
    ** (CaseClauseError) no case clause matching: :query_send
        lib/mariaex/protocol.ex:55: Mariaex.Protocol.dispatch/2
        lib/mariaex/connection.ex:215: Mariaex.Connection.process/2
        lib/mariaex/connection.ex:192: Mariaex.Connection.handle_info/2
        (stdlib) gen_server.erl:599: :gen_server.handle_msg/5
        (stdlib) proc_lib.erl:237: :proc_lib.init_p_do_apply/3

**Comment by liveforeverx** [comment]
Thanks for report, I'll check it today.
