### ISSUE TITLE
How to call stored procedure? 

### ISSUE THREAD

**Issue by aposto** [xerions/mariaex#49]
Is not supported call stored procedure?

**Comment by liveforeverx** [comment]
I'll check this weekend, if it supported or need some extra on client.

**Comment by mguillemot** [comment]
+1 here

The connection process dies when I try to ```CALL something()``` with the following error:

```elixir
[error] GenServer #PID<0.561.0> terminating
Last message: {:tcp, #Port<0.18660>, <<1, 0, 0, 1, 6, 62, 0, 0, 2, 3, 100, 101, 102, 8, 116, 111, 107, 121, 111, 101, 110, 100, 14, 116, 111, 107, 121, 111, 101, 110, 100, 95, 117, 115, 101, 114, 115, 14, 116, 111, 107, 121, 111, 101, 110, 100, 95, 117, ...>>}
State: %{backend_key: nil, opts: [hostname: "localhost", port: 3306, timeout: 5000, otp_app: :xxx, adapter: Ecto.Adapters.MySQL, username: "xxx", password: "xxx", database: "xxx"], parameter_types: [], parameters: [], queue: {[{{:query, "CALL something()", [], [timeout: 5000]}, {#PID<0.440.0>, #Reference<0.0.0.10285>}}], []}, rows: [], seqnum: 0, sock: {Mariaex.Connection.Tcp, #Port<0.18660>}, sock_mod: Mariaex.Connection.Tcp, state: :query_send, state_data: {false, true}, statement: "CALL something()", statement_id: 3, substate: :column_count, tail: "", types: :types_removed}
** (exit) an exception was raised:
    ** (CaseClauseError) no case clause matching: :query_send
        (mariaex) lib/mariaex/protocol.ex:55: Mariaex.Protocol.dispatch/2
        (mariaex) lib/mariaex/connection.ex:215: Mariaex.Connection.process/2
        (mariaex) lib/mariaex/connection.ex:192: Mariaex.Connection.handle_info/2
```

**Comment by liveforeverx** [comment]
Hi, sorry for late answer.

I've pushed to branch stored_procs, and tested with simple stored procedure.
Can somebody check the branch, it it works for all your cases. If it so, I'll push it to master.

**Comment by liveforeverx** [comment]
I've pushed implementation on master. Do not familiar with stored procedures, as we doesn't use it at all, if you can provide some test case for #52 would be very appropriate, I see it in MySQL documentation, but would like to have a test case for it.

**Comment by mguillemot** [comment]
Thank you for the good work! Unfortunately I'm without computer access this week-end, but I'll check the feature and write some tests at the start of next week.

**Comment by liveforeverx** [comment]
@mguillemot, thanks! I've tested myself and have test cases(it was easier, as I thought), I need rethink, if support multiresult statements feature make sense in the light of trying to have most only binary protocol. I think, that multistatement shouldn't be supported.

But, multiple results, what is out of scope at the moment. I will implement it on weekend.

**Comment by aposto** [comment]
Thanks.
I think it seems a lot more developer not often using stored procedures.
I was able to using many stored-procedure.

**Comment by liveforeverx** [comment]
I'll close, as it working.
