### ISSUE TITLE
Race conditions on the prepare statement cache

### ISSUE THREAD

**Issue by josevalim** [xerions/mariaex#61]
I am not sure what is causing them yet but this is a common failure in our builds since we have migrated to 0.2.1: https://travis-ci.org/elixir-lang/ecto/jobs/67628765

One possible root cause can be transactions. Because some tests run inside transactions, if the prepare statement cache is not meant to outlive a transaction, they will be discarded when the transaction rollback or commits. But I may be completely wrong.

**Comment by liveforeverx** [comment]
Thanks for reporting, @josevalim. I'm starting to investigate it.

**Comment by liveforeverx** [comment]
It seems not to be an transactions.

I can reproduce it, have an traced cache add/delete sequences for that case. I'm very close to find the reason. Be back in 1 or 2 hours.

**Comment by liveforeverx** [comment]
Released `v0.2.2`,  which fixes it entirely.
