### ISSUE TITLE
Mariaex incorrectly selects boolean type for TINYINT(4)

### ISSUE THREAD

**Issue by nathanjohnson320** [xerions/mariaex#63]
I have a column of TINYINT(4) with default value of 10 and when I select this column with mariaex it throws the error

```
** (exit) exited in: GenServer.call(#PID<0.135.0>, {:query, "SELECT L0.`weight` FROM `Test` AS L0 WHERE (L0.`id` = 1)", [], [timeout: 5000]}, 5000)
    ** (EXIT) an exception was raised:
        ** (CaseClauseError) no case clause matching: 10
            (mariaex) lib/mariaex/messages.ex:303: Mariaex.Messages.parse_boolean_packet/1
            (mariaex) lib/mariaex/messages.ex:281: Mariaex.Messages.decode_bin_rows/4
            (mariaex) lib/mariaex/protocol.ex:96: Mariaex.Protocol.dispatch/2
            (mariaex) lib/mariaex/connection.ex:219: Mariaex.Connection.process/2
            (mariaex) lib/mariaex/connection.ex:192: Mariaex.Connection.handle_info/2
            (stdlib) gen_server.erl:593: :gen_server.try_dispatch/4
            (stdlib) gen_server.erl:659: :gen_server.handle_msg/5
            (stdlib) proc_lib.erl:237: :proc_lib.init_p_do_apply/3
    (elixir) lib/gen_server.ex:356: GenServer.call/3
    (ecto) lib/ecto/adapters/mysql/connection.ex:31: Ecto.Adapters.MySQL.Connection.query/4
    (ecto) lib/ecto/adapters/sql/worker.ex:24: Ecto.Adapters.SQL.Worker.query!/4
    (ecto) lib/ecto/adapters/sql.ex:187: Ecto.Adapters.SQL.use_worker/3
    (person) lib/person.ex:2: Person.Repo.log/2
    (ecto) lib/ecto/adapters/sql.ex:381: Ecto.Adapters.SQL.all/5
    (ecto) lib/ecto/repo/queryable.ex:20: Ecto.Repo.Queryable.all/4
```

Because in messages.ex it's going to the below line but it should be an integer not a :boolean
```
defp handle_decode_bin_rows({:boolean, :field_type_tiny}, packet),        do: parse_boolean_packet(packet)
```

**Comment by liveforeverx** [comment]
Yes, it is because MySQL doesn't have boolean type. And, INT tiny represents it, but there is no way to get from MySQL tyne(1) or tiny(10) it is (checking).

**Comment by liveforeverx** [comment]
If you will try to save to tiny INT the value 0 or 1, than it is impossible by reading to get right representation, if it is boolean(true, false) or int(0, 1). Is it possible to avoid tiny INTs in your setup?

**Comment by nathanjohnson320** [comment]
No I'm running a model generation script on a legacy database where the TINY ints are already setup. Is there no way to check the NUMERIC_PRECISION column in information schema to grab the size and set it as an integer/boolean based on that?

**Comment by nathanjohnson320** [comment]
Actually I guess you can't because it's always 3 for tinyints.

**Comment by liveforeverx** [comment]
To: @laurocaetano @josevalim 
May be it make sense to decode tiny int always as int and cast 0, 1 to boolean on ecto side?

**Comment by josevalim** [comment]
@liveforeverx yes, we could do that. Once you change the behaviour in mariaex and release new version, please open up an issue in Ecto so we can fix it. Also, please release it as 0.3. :)

**Comment by liveforeverx** [comment]
@josevalim , off course, it is backwards incompatible change.
