### ISSUE TITLE
Support Unix sockets

### ISSUE THREAD

**Issue by chvanikoff** [xerions/mariaex#66]
Currently Mariaex can communicate to MySQL via TCP sockets only. I think Unix sockets support should be added as well because having MySQL and app on the same server is quite a common scenario and in such case communication via Unix socket is preferred.

**Comment by chvanikoff** [comment]
Quick research have shown that there is no simple way to deal with Unix sockets in Erlang (did I miss something?), the most popular library is https://github.com/msantos/gen_unix which is based on https://github.com/msantos/procket and both are not in Hex. I think we could give it a try and in case it will work well for Mariaex, suggest adding these libraries to Hex.

**Comment by liveforeverx** [comment]
Hi! Good idea, we need definitely support it. That is a reason, why transport is abstracted away from other code.

Another option is our gen_socket fork: https://github.com/travelping/gen_socket/tree/driver-poll

For some reasons it should be better (for example it doesn't need root/setuid for using it).

**Comment by liveforeverx** [comment]
Checked our gen_socket it is not platform independent, seems it make for linux only....

**Comment by liveforeverx** [comment]
Hey! I found this: https://github.com/tonyrog/afunix

I'll check if, it works.

**Comment by ericmj** [comment]
If you do this please keep it as an optional dependency, we don't want NIFs in ecto.

**Comment by liveforeverx** [comment]
@ericmj, ok.

**Comment by chvanikoff** [comment]
There's no way to deal with UDS w/out NIFs currently. https://github.com/erlang/otp/pull/612
Probably we can add "only: [:dev, :test]" for this dependency because dev/test envs are the most popular cases for running DB server and the app on the same host
@liveforeverx did u compare afunix against gen_unix (procket)?

**Comment by ericmj** [comment]
The `:only` option inly works for the local project, dependents will never get those dependencies. You need to set `optional: true`.

**Comment by chvanikoff** [comment]
@liveforeverx It seems the time is now: Erlang 19 is released with experimental support for UDS: http://erlang.org/download/otp_src_19.0.readme

**Comment by liveforeverx** [comment]
Support added in `8.4` and `master`
