### ISSUE TITLE
ilike does not work

### ISSUE THREAD

**Issue by imsearchdev** [xerions/mariaex#78]
## Error

Here is the error message:

```
** (exit) an exception was raised:
    ** (Mariaex.Error) (1064): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'ILIKE ?)' at line 1
        (ecto) lib/ecto/adapters/sql.ex:185: Ecto.Adapters.SQL.query!/5
        (ecto) lib/ecto/adapters/sql.ex:478: Ecto.Adapters.SQL.execute/6
        (ecto) lib/ecto/repo/queryable.ex:95: Ecto.Repo.Queryable.execute/5
        (ecto) lib/ecto/repo/queryable.ex:15: Ecto.Repo.Queryable.all/4
```

## Query

I have a very simple ilike query to isolate this: 

```
    search_term = "John%"
    people = Repo.all(
      from p in Find.People,
      where: ilike(p.fname, ^search_term)
    )
```

## Versions

From mix.lock

```
Mariaex: 0.4.3
Phoenix: 1.0.3
Ecto: 1.0.6
Phoenix_ecto: 1.2.0
```

The database:

```
MySQL 5.6.23 
```

**Comment by liveforeverx** [comment]
I'll check it.

**Comment by liveforeverx** [comment]
ilike it is not supported by MySQL.

According to PostgreSQL documentation it is a PostgreSQL extenstion.

```
The key word ILIKE can be used instead of LIKE to make the match case-insensitive according to the active locale. This is not in the SQL standard but is a PostgreSQL extension.
```

I think, this should be resolved on ecto side @josevalim @ericmj ? What do you think about? Should we `ilike` transform to LOWER(string) like LOWER(pattern) or add something to documentation?

**Comment by imsearchdev** [comment]
Documentation or a meaningful runtime exception would be fine alternatives here if this isn't easy to implement. We had done the manual transform to lower(?) like lower(?) before opening this issue so this isn't a blocker, but either supporting ilike or a more meaningful error message would be great.

Thanks.

**Comment by ericmj** [comment]
It could probably be handled in the mysql adapter in ecto by running `LOWER` like you suggested.

**Comment by josevalim** [comment]
Right. In this case he just wants to use `like` as it is case insensitive for MySQL.

**Comment by josevalim** [comment]
We can close this one.
