### ISSUE TITLE
BIT(1) type fails on read

### ISSUE THREAD

**Issue by paulgithub** [xerions/mariaex#89]
When reading a boolean value from the database which is represented as a BIT(1) in the MySQL server (version 5.5.29) The following error is displayed:

** (FunctionClauseError) no function clause matching in Mariaex.Messages.handle_decode_bin_rows/2
     stacktrace:
       (mariaex) lib/mariaex/messages.ex:292: Mariaex.Messages.handle_decode_bin_rows({:bit, :field_type_bit}, <<1, 0, 2, 45, 49, 2, 45, 49, 2, 45, 49, 153, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0>>)
       (mariaex) lib/mariaex/messages.ex:288: Mariaex.Messages.decode_bin_rows/4
       (mariaex) lib/mariaex/connection.ex:153: anonymous fn/4 in Mariaex.Connection.decode/2
       (elixir) lib/enum.ex:1473: Enum."-reduce/3-lists^foldl/2-0-"/3
       (mariaex) lib/mariaex/connection.ex:153: Mariaex.Connection.decode/2
       (mariaex) lib/mariaex/connection.ex:128: Mariaex.Connection.query/4
       (ecto) lib/ecto/adapters/mysql/connection.ex:25: Ecto.Adapters.MySQL.Connection.query/4
       (stdlib) timer.erl:197: :timer.tc/3
       (ecto) lib/ecto/adapters/sql.ex:262: Ecto.Adapters.SQL.query/7
       (ecto) lib/ecto/pool.ex:159: Ecto.Pool.do_run/4
       (ecto) lib/ecto/adapters/sql.ex:247: Ecto.Adapters.SQL.query/6
       (ecto) lib/ecto/adapters/sql.ex:225: Ecto.Adapters.SQL.query/5
       (ecto) lib/ecto/adapters/sql.ex:183: Ecto.Adapters.SQL.query!/5
       (ecto) lib/ecto/adapters/sql.ex:481: Ecto.Adapters.SQL.execute/6
       (ecto) lib/ecto/repo/queryable.ex:95: Ecto.Repo.Queryable.execute/5
       (ecto) lib/ecto/repo/queryable.ex:15: Ecto.Repo.Queryable.all/4
       (ecto) lib/ecto/repo/queryable.ex:44: Ecto.Repo.Queryable.one/4

This is a legacy database and changing the field to a TINYINT(1), which works, will be difficult (impractical).

Versions from mix.lock:
mariaex, "0.6.2"
phoenix, "1.1.2"
ecto, "1.1.1"
phoenix_ecto, "2.0.0"

**Comment by liveforeverx** [comment]
Thanks!

I'll include a fix in upcoming version, on which I'm working now.

**Comment by paulgithub** [comment]
Thanks

**Comment by paulgithub** [comment]
Hi,

Here is a simple update which fixes my issue where using BIT(1) in the database for booleans, it possibly is not the correct fix for all BIT types:

  defp handle_decode_bin_rows({:bit, :field_type_bit}, packet),             do: parse_bit_packet(packet)

  defp parse_bit_packet(packet) do
    << length, raw_value :: size(length)-little-binary, rest :: binary >> = packet
    case raw_value do
      <<value>> ->
        {value, rest}
      _ ->
        {raw_value, rest}
    end
  end

I hope this is helpful.

**Comment by liveforeverx** [comment]
Add simple decoding of bits on mariaex side and to the work for ecto 2.0, should work out of the box in next ecto.

**Comment by liveforeverx** [comment]
Fix merged in ecto and mariaex for the future version.
